services:
  - type: web
    name: taskflow-ai-demo
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt &&
      cd frontend &&
      npm ci &&
      npm run build &&
      cd ..
    startCommand: "uvicorn SRC.api.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:///./taskflow.db